### ISSUE TITLE
New GitHub release

### ISSUE THREAD

**Issue by jitpack-io** [scottyab/safetynethelper#10]
Hi!

Noticed that version 0.1.0 didn't build due to the missing gradle property.
The current master branch works fine:
https://jitpack.io/#scottyab/safetynethelper/67bd94ca9c 

If there was a new release at this commit then that would build as well.

**Comment by scottyab** [comment]
Thanks for heads up! Done, https://github.com/scottyab/safetynethelper/releases/tag/0.1.1

**Comment by jitpack-io** [comment]
Cool! Works like a charm
https://jitpack.io/#scottyab/safetynethelper/0.1.1
