### ISSUE TITLE
I always receive 2 calls when invoke to the method requestTest

### ISSUE THREAD

**Issue by moisesvs** [scottyab/safetynethelper#14]
Hi! 

Now when I invoke to method requestTest I always receive 2 calls onSuccess. I was reviewing the code and I found that first the library sends a callback success and after passes the call to AndroidDeviceVerifier and the AndroidDeviceVerifier returns another success response. In total 2 calls to methods success.

But I only need one call to method success. Why do the library send me 2 calls on success? Will have something fix?

**Comment by bigfishcat** [comment]
https://github.com/scottyab/safetynethelper/blob/master/safetynetlib/src/main/java/com/scottyab/safetynet/SafetyNetHelper.java#L157

This statement should be in else block.

**Comment by moisesvs** [comment]
When could you upload new version of library with this fix?

**Comment by scottyab** [comment]
Thanks for reporting this @moisesvs feel free to put in pull request and I'll review that and the 2 pending PR's and then all being well publish into next version of the lib.

**Comment by scottyab** [comment]
in progress

**Comment by scottyab** [comment]
@moisesvs Fixed in [v0.2.0](https://jitpack.io/#scottyab/safetynethelper/0.2.0) Thanks again for reporting
