### ISSUE TITLE
Add extra validation checks

### ISSUE THREAD

**Issue by scottyab** [scottyab/safetynethelper#2]
Finish the safetynet api response payload validation signature and .apk checksum. 

Update: the code is pushed for these but commented out as I couldn't figure out how the digests for the app signature and .apk checksum were calculated.

**Comment by robsmall** [comment]
It looks like the apk digest is being verified, is it not?

If it is, then https://github.com/scottyab/safetynethelper/pull/13 closes this issue

**Comment by scottyab** [comment]
Fixed thanks @robsmall
