### ISSUE TITLE
payload validation failed

### ISSUE THREAD

**Issue by carlpouliot** [scottyab/safetynethelper#22]
Hi, I always get "safetynet helper response payload validation failed" when i run safetynethelper

my device was rooted, I restored it and did a factory reset. but still, it won't pass

is there anything more I need to do ?

**Comment by TheJaysH** [comment]
Same issue here

**Comment by scottyab** [comment]
Hey, thanks for raising an issue. This library is just a wrapper around the google SafetyNet.API. It's doesn't get any further info apart from than cts pass or fail. Typically a factory reset will revert root but remember SafetyNet isn't just a root checker it's also looking for vulnerabilities.
