### ISSUE TITLE
Support the new integrity check flag returned by Safetynet 

### ISSUE THREAD

**Issue by scottyab** [scottyab/safetynethelper#23]
There's a new flag that is returned by the SafetyNe aTest API, this may explain some of the inconsistent results as noted in #19

**Comment by robsmall** [comment]
Looks like there are 2 new flags: `'basicIntegrity'` and `'extension'` FWIW.

Looks like Google hasn't updated their documentation to talk about the new flags but the following whitepaper has a bit of info on them: http://ipfs.io/ipfs/QmcuVzCVYyYeGuDbUJmSeszGKXYwdBfhJXk6DkiSc5FuZr

**Comment by scottyab** [comment]
Thanks @robsmall appreciated!

**Comment by robsmall** [comment]
No problem! Adding the `basicIntegrity` check should be straight forward. I haven't done enough digging to find out how to use `extension` (yet).

If you find any documentation on this, please let me know :).

**Comment by robsmall** [comment]
Google should be releasing documentation in the near future  for the `basicIntegrity` check.

`extension` can be ignored :)

**Comment by robsmall** [comment]
Looks like Google updated their docs and included the `basicIntegrity` check.

https://developer.android.com/training/safetynet/index.html

They also added code samples if you scroll all the way down to the bottom of the page. I haven't taken a look at them yet, but that should definitely be worth looking at.

**Comment by scottyab** [comment]
Hey @robsmall thanks for the update I'll get on this update this or early next week.

**Comment by scottyab** [comment]
Added as part of v0.3
