### ISSUE TITLE
Safetynet Issue Status{statusCode=NETWORK_ERROR, resolution=null}

### ISSUE THREAD

**Issue by JigarShekh** [scottyab/safetynethelper#38]
We are facing error of “Status{statusCode=NETWORK_ERROR, resolution=null}” event though 4G internet connectivity available in our android device with package name com.safetynet.sample where as sample project is working fine with package name com.scottyab.safetynet.sample

**Comment by parth9966** [comment]
Hello @JigarShekh 

Have you found any solutions on NETWORK_ERROR for same?

**Comment by BulatMukhutdinov** [comment]
Any updates on this?

**Comment by nogweii** [comment]
This is liekly because of the changes to SafetyNet mentioned in #37. Until this application is updated, it'll continue to get these network errors.

**Comment by scottyab** [comment]
resolved, thanks for rasing

**Comment by scottyab** [comment]
Should have closed this back in 2019 when this was resolved
