### ISSUE TITLE
Please submit safetynethelper to the Android TV play store

### ISSUE THREAD

**Issue by jalong4** [scottyab/safetynethelper#42]
Thanks for merging my pull request last year to make your app render properly on Android TV.  I noticed it is still not in the Android TV Play store.  It would help a lot if you could submit it.  thanks,

Jim Long

**Comment by scottyab** [comment]
Hey @jalong4 , I didn't realise it wasn't automatic 🤦‍♂ . Reading up it seems I just need to opt-in but to do that I need to upload at least one screenshot for Android TV on the Store Listing page.

I don't have an Android TV, can you attach some to this thread so I can upload? Thanks

**Comment by jalong4** [comment]
There were screenshots in the pull request.  Let me see if I still have them.

**Comment by jalong4** [comment]
https://github.com/scottyab/safetynethelper/pull/40

Also, we would like to put a link to your app on our partner help center.  I doubt you will have objections but just wanted to let you know.  Also, you might want to make clear when you submit it to the Play Store that it is a developer tool.

Thanks,
JL

**Comment by scottyab** [comment]
Submitted. Awaiting review from Google.

**Comment by jalong4** [comment]
Great, can you let me know when it's live?

**Comment by jalong4** [comment]
Any update?

**Comment by nguyenhieu244** [comment]
@scottyab

**Comment by scottyab** [comment]
yes, it was rejected by Google. I haven't had time to dig into why. I don't have an Android TV to test on. Although have my eye on Phillips Android TV if anyone wants to shout it for me ;) 

> App installation issues
> During testing we experienced installation issues with your app and were unable to successfully evaluate it for Android TV. Please ensure your app can install successfully on Android TV devices and resubmit.

**Comment by jalong4** [comment]
sigh...   Let me see if we can get you an Android TV.  I'll also talk to the Play team.  I'm actually in the Android TV Partner Eng team at Google.

**Comment by scottyab** [comment]
Addressed in #49  version 0.8.0 (v8 of the Sample)
