### ISSUE TITLE
 Lcom/google/android/gms/common/api/Api$zzf

### ISSUE THREAD

**Issue by ljcleyba** [scottyab/safetynethelper#45]
How should i solve this error? Please help

Failed resolution of: Lcom/google/android/gms/common/api/Api$zzf

**Comment by scottyab** [comment]
Hey @ljcleyba I'm not seen that before. Is there a chance it's running on a device without the Google Play services?

**Comment by scottyab** [comment]
Closing as no response and it's been 2yrs
