### ISSUE TITLE
Reported critical issues with version 17.0.0. google play warning

### ISSUE THREAD

**Issue by ben-j69** [scottyab/safetynethelper#59]
Hello,

Using the version 0.8.0 of the library a warning is now displayed when uploading the app in the play store:

> Le développeur de play-services-safetynet (com.google.android.gms:play-services-safetynet) a signalé des problèmes critiques pour la version 17.0.0. Pensez à passer à une version plus récente avant de publier une nouvelle release.

It means the version 17 of safety net must not be used anymore, can you please release a new version with an update version of the safety net library to avoid any issue ?

Thanks

**Comment by scottyab** [comment]
Please update to 0.9.0 Thanks

**Comment by ben-j69** [comment]
> Please update to 0.9.0 Thanks

Hello, we didn't find the version 0.9.0, so we took the 0.10.0, is it ok ?
